/*
 * File: app/store/Protokoll.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.store.Protokoll', {
    extend: 'Ext.data.Store',

    requires: [
        'hurricane.model.Protokoll',
        'Ext.data.proxy.Direct',
        'hurricane.DirectAPI',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Protokoll',
            autoSync: true,
            model: 'hurricane.model.Protokoll',
            proxy: {
                type: 'direct',
                api: {
                    create: 'ProtokollQuery.createProtokoll',
                    read: 'ProtokollQuery.readProtokoll',
                    update: 'ProtokollQuery.updateProtokoll',
                    destroy: 'ProtokollQuery.deleteProtokoll'
                },
                reader: {
                    type: 'json'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true
                }
            }
        }, cfg)]);
    }
});