/*
 * File: app/store/StatistikAbgang.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.store.StatistikAbgang', {
    extend: 'Ext.data.Store',

    requires: [
        'hurricane.model.StatistikAufnamhe',
        'Ext.data.proxy.Direct',
        'hurricane.DirectAPI',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StatistikAbgang',
            autoLoad: true,
            model: 'hurricane.model.StatistikAufnamhe',
            proxy: {
                type: 'direct',
                directFn: 'StatistikQuery.getAbgang',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});