/*
 * File: app/view/addPatient.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.addPatient', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.addpatient',

    requires: [
        'hurricane.view.EditPatientViewModel1',
        'hurricane.view.EditPatientViewController1',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'addpatient',
    viewModel: {
        type: 'addpatient'
    },
    modal: true,
    id: 'addPatient',
    width: 250,
    frameHeader: false,
    header: false,
    manageHeight: false,
    title: 'Patienten Anzeigen',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            reference: 'form',
            id: 'frmAddPatient',
            itemId: 'myform',
            bodyPadding: '10 10 10 25',
            title: 'Patientendaten',
            titleAlign: 'center',
            items: [
                {
                    xtype: 'displayfield',
                    hidden: true,
                    fieldLabel: 'Patient Id',
                    name: 'patientID',
                    submitValue: true
                },
                {
                    xtype: 'textfield',
                    id: 'inpName',
                    width: 200,
                    fieldLabel: 'Name',
                    hideLabel: true,
                    name: 'Name',
                    readOnly: false,
                    allowBlank: false,
                    emptyText: 'Name'
                },
                {
                    xtype: 'textfield',
                    width: 200,
                    fieldLabel: 'Vorname',
                    hideLabel: true,
                    name: 'Vorname',
                    readOnly: false,
                    allowBlank: false,
                    emptyText: 'Vorname'
                },
                {
                    xtype: 'datefield',
                    width: 200,
                    fieldLabel: 'Geburtsdatum',
                    hideLabel: true,
                    name: 'Geburtsdatum',
                    readOnly: false,
                    emptyText: 'Geburtsdatum',
                    format: 'd.m.Y',
                    submitFormat: 'Y-m-d'
                },
                {
                    xtype: 'textfield',
                    width: 200,
                    fieldLabel: 'Strasse',
                    hideLabel: true,
                    name: 'Strasse',
                    readOnly: false,
                    emptyText: 'Strasse'
                },
                {
                    xtype: 'textfield',
                    width: 200,
                    fieldLabel: 'Plz',
                    hideLabel: true,
                    name: 'PLZ',
                    readOnly: false,
                    emptyText: 'Plz'
                },
                {
                    xtype: 'textfield',
                    width: 200,
                    fieldLabel: 'Ort',
                    hideLabel: true,
                    name: 'Ort',
                    readOnly: false,
                    emptyText: 'Ort'
                },
                {
                    xtype: 'combobox',
                    id: 'frmFldGeschlecht1',
                    width: 200,
                    fieldLabel: 'Geschlecht',
                    hideLabel: true,
                    name: 'GeschlechtID',
                    readOnly: false,
                    allowBlank: false,
                    emptyText: 'Geschlecht',
                    displayField: 'Beschreibung',
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'Geschlecht',
                    valueField: 'GeschlechtID'
                },
                {
                    xtype: 'container',
                    hidden: true,
                    padding: 10,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Speichern',
                            listeners: {
                                click: {
                                    fn: 'onSave',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Abbrechen',
                            listeners: {
                                click: {
                                    fn: 'onCancel',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onFrmEditPatient1AfterRender'
            }
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    },

    onFrmEditPatient1AfterRender: function(component, eOpts) {

    },

    onWindowAfterRender: function(component, eOpts) {
        var form         = this.getReferences().form.getForm();
        var newRecord = Ext.create('hurricane.model.Patient');

        form.reset();

        form.loadRecord(newRecord);
    }

});