/*
 * File: app/view/Dateneingabe.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Dateneingabe', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dateneingabe',

    requires: [
        'hurricane.view.DateneingabeViewModel',
        'hurricane.view.DateneingabeViewController',
        'hurricane.view.PatietenListe',
        'hurricane.view.addPatient',
        'hurricane.view.Protokoll',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    controller: 'dateneingabe',
    viewModel: {
        type: 'dateneingabe'
    },
    dock: 'left',
    bodyBorder: true,
    frameHeader: false,
    header: false,
    manageHeight: false,
    title: 'My Panel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'patietenliste',
            dock: 'left',
            layout: 'fit',
            title: 'PatientenListe',
            flex: 1
        }
    ],
    items: [
        {
            xtype: 'container',
            flex: 1,
            maxHeight: 100000,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 0,
                    height: 438,
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'addpatient',
                            maxWidth: 300,
                            flex: 1
                        },
                        {
                            xtype: 'protokoll',
                            layout: 'vbox',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    dock: 'bottom',
                    height: 55,
                    items: [
                        {
                            xtype: 'button',
                            margin: '20 10 10 10 ',
                            text: 'Speichern',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '20 10 10 10',
                            width: 150,
                            text: 'Abbrechen',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});