/*
 * File: app/view/DateneingabeViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.DateneingabeViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dateneingabe',

    requires: [
        'hurricane.model.Patient'
    ],

    onButtonClick: function (button, e, eOpts) {
        var form = Ext.getCmp('frmAddPatient').getForm(),
            newRecord = Ext.create('hurricane.model.Patient'),
            store = Ext.getStore('Patient');

        debugger;

        if (form.isValid()) {
            form.updateRecord();
            var temp = store.add(form.getRecord());
            console.log(temp);

            form.reset();
            form.loadRecord(newRecord);

        }


    },

    onButtonClick1: function (button, e, eOpts) {
        var form = Ext.getCmp('frmAddPatient').getForm(),
            newRecord = Ext.create('hurricane.model.Patient');

        form.reset();
        form.loadRecord(newRecord);
    },

    onPanelAfterRender: function (component, eOpts) {
        var form = Ext.getCmp('frmAddPatient').getForm().findField('Name').focus();
    }

});
