/*
 * File: app/view/DateneingabeViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.DateneingabeViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dateneingabe',

    onButtonClick: function(button, e, eOpts) {
        var form         = Ext.getCmp('frmAddPatient').getForm(),
            form2        = Ext.getCmp('frmInputProtokoll').getForm(),
            newRecord    = Ext.create('hurricane.model.Patient'),
            // newRecord2    = Ext.create('hurricane.model.Protokoll'),
            store        = Ext.getStore('Patient'),
            // store2		 = Ext.getStore('Protokoll'),
            valid		 = true;

        if (!form.isValid()) {
            valid = false;
        }

        if (!form2.isValid()) {
            vaild = false;
        }

        //if (form.isValid() && form2.isValid()){
        if (valid){
            form.updateRecord();
            var temp = store.add(form.getRecord());

            setTimeout(function(){
                form2.findField('PatientenID').setValue(temp[0].data.patientID);
                form2.updateRecord();
                var temp2 = store2.add(form2.getRecord());


                form.reset();
                form.loadRecord(newRecord);
                form2.reset();
                form2.loadRecord(newRecord2);
            }, 500);


        }



    },

    onButtonClick1: function(button, e, eOpts) {
        var form         = Ext.getCmp('frmAddPatient').getForm(),
            newRecord    = Ext.create('hurricane.model.Patient');

        form.reset();
        form.loadRecord(newRecord);
    },

    onPanelAfterRender: function(component, eOpts) {
        var form = Ext.getCmp('frmAddPatient').getForm().findField('Name').focus();
    }

});
