/*
 * File: app/view/Dateneingabe.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Dateneingabe', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dateneingabe',

    requires: [
        'hurricane.view.DateneingabeViewModel',
        'hurricane.view.DateneingabeViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Template',
        'Ext.XTemplate'
    ],

    controller: 'dateneingabe',
    viewModel: {
        type: 'dateneingabe'
    },
    dock: 'left',
    width: 300,
    bodyBorder: true,
    frameHeader: false,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            width: 300,
            title: 'Patienten Liste',
            store: 'Patient',
            viewConfig: {
                border: 1,
                dock: 'left',
                width: 300
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'patientID',
                    text: 'Patient Id'
                },
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '{Vorname} {Name} <br> {Geburtsdatum:date(\'d.m.Y\')}'
                    ],
                    width: 300,
                    dataIndex: 'Name',
                    text: 'Name'
                }
            ],
            listeners: {
                itemdblclick: 'onGridpanelItemDblClick'
            }
        }
    ]

});