/*
 * File: app/view/Home.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Home', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.home',

    requires: [
        'hurricane.view.HomeViewModel',
        'hurricane.view.PatientenListView',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'home'
    },

    items: [
        {
            xtype: 'patientenlistview'
        }
    ]

});