/*
 * File: app/view/PatietenListe.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.PatietenListe', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patietenliste',

    requires: [
        'hurricane.view.PatietenListeViewModel',
        'hurricane.view.PatietenListeViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Template',
        'Ext.XTemplate'
    ],

    controller: 'patietenliste',
    viewModel: {
        type: 'patietenliste'
    },
    width: 250,
    frameHeader: false,
    header: false,
    title: 'My Panel',

    items: [
        {
            xtype: 'gridpanel',
            width: 250,
            title: 'Patienten Liste',
            store: 'Patient',
            viewConfig: {
                border: 1,
                dock: 'left',
                width: 250
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'patientID',
                    text: 'Patient Id'
                },
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '{Vorname} {Name} <br> {Geburtsdatum:date(\'d.m.Y\')}'
                    ],
                    width: 250,
                    dataIndex: 'Name',
                    text: 'Name'
                }
            ],
            listeners: {
                itemdblclick: 'onGridpanelItemDblClick'
            }
        }
    ]

});