/*
 * File: app/view/PatientenListView.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.PatientenListView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patientenlistview',

    requires: [
        'hurricane.view.PatientenListViewViewModel',
        'hurricane.view.PatientenListViewViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Date',
        'Ext.grid.filters.Filters'
    ],

    controller: 'patientenlistview',
    viewModel: {
        type: 'patientenlistview'
    },
    dock: 'top',
    scrollable: true,
    layout: 'fit',
    frameHeader: false,
    header: false,
    title: 'My Panel',

    items: [
        {
            xtype: 'gridpanel',
            reference: 'list',
            id: 'grdPatientenListe',
            scrollable: true,
            manageHeight: false,
            title: 'Patienten Liste',
            forceFit: true,
            store: 'Patient',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Vorname',
                    text: 'Vorname'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name',
                    text: 'Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'Geburtsdatum',
                    text: 'Geburtsdatum',
                    format: 'd.m.Y'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Strasse',
                    text: 'Strasse'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PLZ',
                    text: 'Plz'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Ort',
                    text: 'Ort'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        switch (value) {
                            case '2': return 'männlich';
                            case '1': return 'weiblich';
                            default: return 'unbekannt';
                        }

                    },
                    dataIndex: 'GeschlechtID',
                    text: 'Geschlecht'
                }
            ],
            listeners: {
                select: 'select',
                itemdblclick: 'onGridpanelItemDblClick'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        }
    ]

});