/*
 * File: app/view/Protokoll.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Protokoll', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.protokoll',

    requires: [
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Text',
        'Ext.form.field.Time',
        'Ext.layout.container.Fit',
        'Ext.layout.container.VBox',
        'hurricane.view.ProtokollViewController',
        'hurricane.view.ProtokollViewModel'
    ],

    controller: 'protokoll',
    viewModel: {
        type: 'protokoll'
    },
    id: 'pnlProtokoll',
    shrinkWrap: 0,
    width: 250,
    layout: 'fit',
    frameHeader: false,
    header: false,
    manageHeight: false,
    defaultListenerScope: true,

    items: [
        {
            // xtype: 'form',
            // reference: 'form',
            // id: 'frmInputProtokoll',
            // itemId: 'myform3',
            width: 250,
            layout: 'vbox',
            // bodyPadding: '10 10 10 25',
            // manageHeight: false,
            // title: 'Protokolldaten',
            // titleAlign: 'center',
            listeners: {
                afterrender: 'onFormAfterRender'
            },
            items: [

            ]
        }
    ],

    onFormAfterRender: function(component, eOpts) {
        // var form         = this.getReferences().form.getForm();
        // var newRecord = Ext.create('hurricane.model.Protokoll');
        //
        // // Clear form
        // form.reset();
        //
        // // Set record
        // form.loadRecord(newRecord);
    }

});