/*
 * File: app/view/showProtokoll.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.showProtokoll', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.showprotokoll',

    requires: [
        'hurricane.view.showProtokollViewModel',
        'hurricane.view.showProtokollViewController',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'showprotokoll',
    viewModel: {
        type: 'showprotokoll'
    },
    width: 400,
    frameHeader: false,
    header: false,
    title: 'My Panel',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            itemId: 'myform2',
            bodyPadding: '20 20 20 25',
            frameHeader: false,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'displayfield',
                    hidden: true,
                    width: 180,
                    fieldLabel: 'Protokoll Id',
                    name: 'ProtokollID'
                },
                {
                    xtype: 'displayfield',
                    hidden: true,
                    width: 180,
                    fieldLabel: 'Patienten Id',
                    name: 'PatientenID'
                },
                {
                    xtype: 'datefield',
                    width: 350,
                    fieldLabel: 'Eingangs Datum',
                    labelWidth: 150,
                    name: 'EingangsDatum',
                    readOnly: true
                },
                {
                    xtype: 'numberfield',
                    width: 350,
                    fieldLabel: 'Patienten Nummer',
                    labelWidth: 150,
                    name: 'PatientenNummer',
                    readOnly: true
                },
                {
                    xtype: 'datefield',
                    width: 350,
                    fieldLabel: 'Aufnahme Zeit',
                    labelWidth: 150,
                    name: 'AufnahmeZeit',
                    readOnly: true
                },
                {
                    xtype: 'combobox',
                    width: 350,
                    fieldLabel: 'Aufnahme Id',
                    labelWidth: 150,
                    name: 'AufnahmeID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    width: 350,
                    fieldLabel: 'Aufnahme Ktw',
                    labelWidth: 150,
                    name: 'AufnahmeKTW',
                    readOnly: true
                },
                {
                    xtype: 'datefield',
                    width: 350,
                    fieldLabel: 'Abgang Zeit',
                    labelWidth: 150,
                    name: 'AbgangZeit',
                    readOnly: true
                },
                {
                    xtype: 'combobox',
                    width: 350,
                    fieldLabel: 'Abgang Id',
                    labelWidth: 150,
                    name: 'AbgangID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    width: 350,
                    fieldLabel: 'Abgang Uebergabe',
                    labelWidth: 150,
                    name: 'AbgangUebergabe',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    width: 350,
                    fieldLabel: 'Abgang Ziel',
                    labelWidth: 150,
                    name: 'AbgangZiel',
                    readOnly: true
                },
                {
                    xtype: 'combobox',
                    width: 350,
                    fieldLabel: 'Diagnose Id',
                    labelWidth: 150,
                    name: 'DiagnoseID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    width: 350,
                    fieldLabel: 'Diagnose Sonstiges',
                    labelWidth: 150,
                    name: 'DiagnoseSonstiges',
                    readOnly: true
                },
                {
                    xtype: 'numberfield',
                    width: 350,
                    fieldLabel: 'Helfer Nr1',
                    labelWidth: 150,
                    name: 'HelferNr1',
                    readOnly: true
                },
                {
                    xtype: 'numberfield',
                    width: 350,
                    fieldLabel: 'Helfer Nr2',
                    labelWidth: 150,
                    name: 'HelferNr2',
                    readOnly: true
                },
                {
                    xtype: 'container',
                    hidden: true,
                    padding: 10,
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Save',
                            listeners: {
                                click: 'onSave'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancel',
                            listeners: {
                                click: 'onCancel'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});