/*
 * File: app/view/Start.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Start', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.start',

    requires: [
        'hurricane.view.StartViewModel',
        'hurricane.view.Dateneingabe',
        'hurricane.view.PatientenListView',
        'hurricane.view.Statistik',
        'Ext.tab.Tab',
        'Ext.Img',
        'Ext.tab.Panel'
    ],

    viewModel: {
        type: 'start'
    },
    manageHeight: false,
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            manageHeight: false,
            title: 'Home',
            items: [
                {
                    xtype: 'panel',
                    frameHeader: false,
                    header: false,
                    manageHeight: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            maxWidth: 300,
                            padding: '50 0 0 0',
                            src: 'resources/img/drk.png'
                        },
                        {
                            xtype: 'image',
                            height: 300,
                            margin: '50  0 0 0',
                            padding: '',
                            src: 'resources/img/hu-website-vorschau.jpg'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            manageHeight: false,
            title: 'Dateneingabe',
            items: [
                {
                    xtype: 'dateneingabe',
                    layout: {
                        type: 'vbox',
                        align: 'middle',
                        pack: 'center'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'Suche',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'patientenlistview',
                    layout: 'absolute',
                    flex: 1
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: 'Statistik',
            items: [
                {
                    xtype: 'statistik'
                }
            ]
        }
    ]

});