/*
 * File: app/view/Start.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.Start', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.start',

    requires: [
        'hurricane.view.StartViewModel',
        'hurricane.view.Dateneingabe',
        'Ext.panel.Panel',
        'Ext.tab.Tab',
        'Ext.Img'
    ],

    viewModel: {
        type: 'start'
    },
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            title: 'Home',
            items: [
                {
                    xtype: 'panel',
                    frameHeader: false,
                    header: false,
                    manageHeight: false,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'image',
                            src: 'resources/img/drk.png'
                        },
                        {
                            xtype: 'image',
                            height: 500,
                            src: 'resources/img/hu-website-vorschau.jpg'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            manageHeight: false,
            title: 'Dateneingabe',
            items: [
                {
                    xtype: 'dateneingabe'
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'Suche'
        }
    ]

});