/*
 * File: app/view/StatistikViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.view.StatistikViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.statistik',

    onPanelBeforeShow: function(component, eOpts) {
        console.log(Ext.getStore('Patient').totalCount);
        Ext.getCmp('txtPatientGesamt').setValue(Ext.getStore('Patient').totalCount);
    },

    onPanelAfterRender: function(component, eOpts) {
        this.onPanelBeforeShow();
    },

    onPanelShow: function(component, eOpts) {
        Ext.getStore('StatistikAufnahme').load();
    },

    onPanelShow1: function(component, eOpts) {
        Ext.getStore('StatistikDiagnose').load();
    },

    onPanelShow2: function(component, eOpts) {
        Ext.getStore('StatistikAbgang').load();
    }

});
