/*
 * File: app/model/Patient.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.model.Patient', {
    extend: 'Ext.data.Model',
    alias: 'model.patient',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'patientID'
        },
        {
            type: 'string',
            name: 'Name'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'Vorname'
        },
        {
            type: 'date',
            name: 'Geburtsdatum',
            dateWriteFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'Strasse'
        },
        {
            type: 'string',
            name: 'PLZ'
        },
        {
            type: 'string',
            name: 'Ort'
        },
        {
            type: 'string',
            name: 'GeschlechtID'
        }
    ]
});