/*
 * File: app/model/Patient.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.model.Patient', {
    extend: 'Ext.data.Model',
    alias: 'model.patient',

    requires: [
    ],

    fields: [
        {
            type: 'int',
            name: 'patientID'
        },
        {
            type: 'string',
            name: 'Name',
            sortType: 'asUCString'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'Vorname'
        },
        {
            type: 'date',
            name: 'Geburtsdatum',
            dateWriteFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'Strasse'
        },
        {
            type: 'string',
            name: 'PLZ'
        },
        {
            type: 'string',
            name: 'Ort'
        },
        {
            type: 'string',
            name: 'GeschlechtID'
        },
        {
            type: 'date',
            name: 'EingangsDatum',
            dateWriteFormat: 'Y-m-d'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'PatientenNummer',
            unique: true
        },
        {
            type: 'date',
            name: 'AufnahmeZeit',
            dateFormat: 'H:i:s'
        },
        {
            type: 'int',
            name: 'AufnahmeID'
        },
        {
            type: 'string',
            name: 'AufnahmeKTW'
        },
        {
            type: 'date',
            name: 'AbgangZeit',
            dateFormat: 'H:i:s'
        },
        {
            type: 'int',
            name: 'AbgangID'
        },
        {
            type: 'string',
            name: 'AbgangUebergabe'
        },
        {
            name: 'AbgangZiel'
        },
        {
            type: 'int',
            name: 'DiagnoseID'
        },
        {
            type: 'string',
            name: 'DiagnoseSonstiges'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'HelferNr1'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'HelferNr2'
        }
    ]
});