/*
 * File: app/model/Protokoll.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hurricane.model.Protokoll', {
    extend: 'Ext.data.Model',
    alias: 'model.protokoll',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'ProtokollID'
        },
        {
            type: 'date',
            name: 'EingangsDatum',
            dateFormat: 'd.m.Y',
            dateWriteFormat: 'Y-m-d'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'PatientenNummer'
        },
        {
            type: 'date',
            name: 'AufnahmeZeit',
            dateFormat: 'H:i',
            dateWriteFormat: 'H:i'
        },
        {
            type: 'int',
            name: 'AufnahmeID'
        },
        {
            type: 'string',
            name: 'AufnahmeKTW'
        },
        {
            type: 'date',
            name: 'AbgangZeit',
            dateFormat: 'H:i',
            dateWriteFormat: 'H:i'
        },
        {
            type: 'int',
            name: 'AbgangID'
        },
        {
            type: 'string',
            name: 'AbgangUebergabe'
        },
        {
            name: 'AbgangZiel'
        },
        {
            type: 'int',
            name: 'DiagnoseID'
        },
        {
            type: 'string',
            name: 'DiagnoseSonstiges'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'HelferNr1'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'HelferNr2'
        }
    ]
});